
package mintwire.jframes;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.Box;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import mintwire.PartyState;

import mintwire.p2pmodels.MintNode;
import mintwire.p2pmodels.messages.PeerInfo;
import mintwire.panels.peerlist.PartyPeerPanel;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import rice.p2p.scribe.Topic;
import rice.pastry.NodeHandle;

/**
 *
 * @author Lavinia
 */
public class PassphraseGiver extends javax.swing.JFrame {
    private JLabel label;
    private Box box;
    private MintNode mintNode;
    private RSyntaxTextArea textArea;
    private static PassphraseGiver instance = null;

    public static PassphraseGiver getInstance(MintNode mintNode, RSyntaxTextArea textArea, Box box) {
        return instance = new PassphraseGiver(mintNode, textArea, box);
    }

    private PassphraseGiver(MintNode mintNode, RSyntaxTextArea textArea, Box box) {
        setTitle("Passphrase");
        this.mintNode = mintNode;
        this.textArea = textArea;
        this.box=box;
        initComponents();
    }

    private PassphraseGiver() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        passTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(49, 46, 54));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(97, 214, 28));
        jLabel2.setText("Enter the party's passphrase below:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 37));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 93, 67));
        jLabel1.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/mintwire/res/pngs/enter-code.png")).getImage().getScaledInstance(64, 64, Image.SCALE_SMOOTH)));

        passTextField.setBackground(new java.awt.Color(49, 46, 54));
        passTextField.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        passTextField.setForeground(new java.awt.Color(204, 204, 204));
        passTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passTextFieldKeyTyped(evt);
            }
        });
        jPanel1.add(passTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 128, 190, 37));

        jButton1.setText("Enter");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 177, -1, 36));

        jButton2.setText("Cancel");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 177, -1, 36));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        if (mintNode.getPartyClient().getAvailableTopics().containsKey(passTextField.getText())) {
            Topic topic = mintNode.getPartyClient().getAvailableTopics().get(passTextField.getText()).getTopic();
            mintNode.getPartyClient().setPublishInfo(mintNode, textArea,box);
            NodeHandle hostHandle=mintNode.getPartyClient().getAvailableTopics().get(passTextField.getText()).getPeerInfo().getNodeHandle();
            mintNode.getPartyClient().joinTopic(mintNode.getNode().getLocalHandle(), topic,hostHandle);
            System.err.println(topic.toString());
            //mintNode.getPartyClient().startPublishTask();
            
            
            PeerInfo hostInfo=mintNode.getPartyClient().getAvailableTopics().get(passTextField.getText()).getPeerInfo();
            PartyPeerPanel partyPeerPanel = new PartyPeerPanel(new PeerInfo(hostInfo.getNodeHandle(), hostInfo.getAlias(), "host", false));
            partyPeerPanel.setPreferredSize(new Dimension(176, 132));
            
            PartyPeerPanel partyPeerPanel2 = new PartyPeerPanel(new PeerInfo(mintNode.getNode().getLocalHandle(), mintNode.getNode().alias, mintNode.getNode().status, false));
            partyPeerPanel2.setPreferredSize(new Dimension(176, 132));
            
            
            box.add(partyPeerPanel);
            box.revalidate();
            box.add(partyPeerPanel2);
            box.revalidate();
            box.add(Box.createVerticalGlue());
            box.revalidate();
            MintwireClientGUI.partyState = PartyState.Joined;
        }else {
             label=new JLabel("<html><center>Cannot join party as the passphrase is incorrect!");
                    label.setHorizontalAlignment(SwingConstants.CENTER);
                    JOptionPane.showMessageDialog(null, label, "Incorrect Passphrase", JOptionPane.INFORMATION_MESSAGE);
        }
        
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void passTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passTextFieldKeyTyped
        // TODO add your handling code here:
        boolean max = passTextField.getText().length() >= 6;
        if (max) {
            evt.consume();
    }//GEN-LAST:event_passTextFieldKeyTyped

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassphraseGiver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassphraseGiver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassphraseGiver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassphraseGiver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassphraseGiver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField passTextField;
    // End of variables declaration//GEN-END:variables
}
